apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.chatbot.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.chatbot.config.labels | nindent 4 }}
data:
    SERVER_PORT: {{ .Values.chatbot.port | quote }}
    IDENTITY_SERVICE: {{ .Values.identity.service.name }}:{{ .Values.identity.port }}
    WEB_SERVICE: {{ .Values.web.service.name }}:{{ .Values.web.port }}
    TLS_ENABLED: {{ .Values.tlsEnabled | quote }}
    DB_HOST: {{ .Values.postgresdb.service.name }}
    DB_USER: {{ .Values.postgresdb.config.postgresUser }}
    DB_PASSWORD: {{ .Values.postgresdb.config.postgresPassword }}
    DB_NAME: {{ .Values.postgresdb.config.postgresDbName }}
    DB_PORT: {{ .Values.postgresdb.port | quote }}
    MONGO_DB_HOST: {{ .Values.mongodb.service.name }}
    MONGO_DB_PORT: {{ .Values.mongodb.port | quote }}
    MONGO_DB_USER: {{ .Values.mongodb.config.mongoUser }}
    MONGO_DB_PASSWORD: {{ .Values.mongodb.config.mongoPassword }}
    MONGO_DB_NAME: {{ .Values.mongodb.config.mongoDbName }}
    CHATBOT_OPENAI_API_KEY: {{ .Values.openAIApiKey }}
    DEFAULT_MODEL: {{ .Values.chatbot.config.defaultModel | quote }}
    CHROMA_PERSIST_DIRECTORY: {{ .Values.chatbot.config.chromaPersistDirectory | quote }}
